# Project information
site_name: Mr School's documentation for Tin h·ªçc GDPT 2018
site_url: https://vtchitruong.github.io/
site_author: Martin Donath
site_description: >-
  Gi√∫p b·∫°n n·∫Øm b·∫Øt ki·∫øn th·ª©c c∆° b·∫£n c·ªßa m√¥n Tin h·ªçc c·∫•p trung h·ªçc ph·ªï th√¥ng.  
  Ti·∫øp thu d·ªÖ d√†ng. Tra c·ª©u thu·∫≠n ti·ªán. Xem ƒë∆∞·ª£c ·ªü m·ªçi n∆°i c√≥ net, tr√™n nhi·ªÅu lo·∫°i m√°y, b·∫•t k·ªÉ t∆∞ th·∫ø.

# Repository
repo_name: vtchitruong.github.io
repo_url: https://github.com/vtchitruong/vtchitruong.github.io

# Copyright
copyright: Copyright &copy; 2023 Mr School

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: light blue
      toggle:
      #   icon: material/lightbulb-outline
      #   name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: lime
      toggle:
      #   icon: material/lightbulb
      #   name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: G-406896385
    feedback:
      title: B√†i vi·∫øt tr√™n c√≥ gi√∫p √≠ch g√¨ cho b·∫°n kh√¥ng?</br>H√£y n√°n l·∫°i "qu√°nh gi√°" m·ªôt c√°i cho ch·ªß th·ªõt th√™m c·∫£m h·ª©ng, ho·∫∑c c·∫£m... l·∫°nh üòÑ
      ratings:
        - icon: material/heart
          name: This post definitely needs improvement.
          data: 1
          note: >-
            C·∫£m ∆°n b·∫°n ƒë√£ ƒë√°nh gi√°. Ch√∫ng t√¥i ƒëang x√¢y d·ª±ng form ph·∫£n h·ªìi √Ω ki·∫øn. Mong l·∫ßn t·ªõi s·∫Ω nh·∫≠n ƒë∆∞·ª£c g√≥p √Ω c·ªßa b·∫°n.
        - icon: material/heart
          name: This post could be improved.
          data: 2
          note: >- 
            C·∫£m ∆°n b·∫°n ƒë√£ ƒë√°nh gi√°. Ch√∫ng t√¥i ƒëang x√¢y d·ª±ng form ph·∫£n h·ªìi √Ω ki·∫øn. Mong l·∫ßn t·ªõi s·∫Ω nh·∫≠n ƒë∆∞·ª£c g√≥p √Ω c·ªßa b·∫°n.
        - icon: material/heart
          name: I'm not sure. This post is passable.
          data: 3
          note: >-
            C·∫£m ∆°n b·∫°n ƒë√£ ƒë√°nh gi√°. Ch√∫ng t√¥i ƒëang x√¢y d·ª±ng form ph·∫£n h·ªìi √Ω ki·∫øn. Mong l·∫ßn t·ªõi s·∫Ω nh·∫≠n ƒë∆∞·ª£c g√≥p √Ω c·ªßa b·∫°n.
        - icon: material/heart
          name: This post is quite useful.
          data: 4
          note: >-
            C·∫£m ∆°n b·∫°n ƒë√£ ƒë√°nh gi√°. Ch√∫ng t√¥i ƒëang x√¢y d·ª±ng form ph·∫£n h·ªìi √Ω ki·∫øn. Mong l·∫ßn t·ªõi s·∫Ω nh·∫≠n ƒë∆∞·ª£c g√≥p √Ω c·ªßa b·∫°n.
        - icon: material/heart
          name: This post is absolutely useful.
          data: 5
          note: >-
            C·∫£m ∆°n b·∫°n ƒë√£ ƒë√°nh gi√°. Ch√∫ng t√¥i ƒëang x√¢y d·ª±ng form ph·∫£n h·ªìi √Ω ki·∫øn. Mong l·∫ßn t·ªõi s·∫Ω nh·∫≠n ƒë∆∞·ª£c g√≥p √Ω c·ªßa b·∫°n.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      # options:
        # custom_icons:
        #   - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets


## Custom theme additions
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Getting started: getting-started.md
#   - Creating your site: creating-your-site.md
#   - Publishing your site: publishing-your-site.md
#   - Customization: customization.md
#   - Browser support: browser-support.md
#   - Philosophy: philosophy.md
#   - Alternatives: alternatives.md
#   - License: license.md
#   - Changelog:
#     - changelog/index.md
#     - How to upgrade: upgrade.md
#   - Contributing:
#     - contributing/index.md
#     - Reporting a bug: contributing/reporting-a-bug.md
#     - Reporting a docs issue: contributing/reporting-a-docs-issue.md
#     - Requesting a change: contributing/requesting-a-change.md
#     - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
#   - Guides:
#     - Creating a reproduction: guides/creating-a-reproduction.md
#   - FAQ:
#     - Sponsoring: faq/sponsoring.md
  - L·ªõp 10:
    - Kh√°i qu√°t ch∆∞∆°ng tr√¨nh h·ªçc: grade-10/grade-10-index.md
    - Ch·ªß ƒë·ªÅ A:
      - grade-10/topic-A/data-vs-information.md
      - grade-10/topic-A/data-measurement-unit.md      
      - grade-10/topic-A/superiority-of-digital-devices.md
      - grade-10/topic-A/data-representation-in-cs.md
      - grade-10/topic-A/convert-numbers-to-different-systems.md
    - Ch·ªß ƒë·ªÅ F:
      - grade-10/topic-F/conditional-statement-if.md
      - grade-10/topic-F/for-loop.md
      - grade-10/topic-F/while-loop.md
      - grade-10/topic-F/list.md
      - grade-10/topic-F/string.md
  - L·ªõp 11:
    - Kh√°i qu√°t ch∆∞∆°ng tr√¨nh h·ªçc: grade-11/grade-11-index.md
    - Ch·ªß ƒë·ªÅ A:
      - grade-11/topic-A/os-and-application.md
      - grade-11/topic-A/open-source-software.md
      - grade-11/topic-A/os-history.md      
    - Ch·ªß ƒë·ªÅ F:
      - grade-11/topic-F/array.md
      - grade-11/topic-F/linked-list.md
      - grade-11/topic-F/searching-algorithm.md
      - grade-11/topic-F/sorting-algorithm.md
      - grade-11/topic-F/algorithmic-complexity.md
  - L·ªõp 12:
    - grade-12/grade-12-index.md
  - N√¢ng cao:
    - advanced/advanced-index.md
    - ƒê·ªì th·ªã:
      - DFS: advanced/graph/dfs.md
      - BFS: advanced/graph/bfs.md
  - MOS:
    - MOS 2016: mos/mos-2016-index.md
    # - Word 2016: word-2016-index.md
      # - Word 2016 Core Practice Exam 1 Training:
    # - Excel 2016 Core Practice Exam 1 Training:
    - PowerPoint 2016:
      - Practice Exam 1:
        - Project 1: mos/powerpoint-2016/exam-1/project-1.md
        - Project 2: mos/powerpoint-2016/exam-1/project-2.md
        - Project 3: mos/powerpoint-2016/exam-1/project-3.md
        - Project 4: mos/powerpoint-2016/exam-1/project-4.md
        - Project 5: mos/powerpoint-2016/exam-1/project-5.md
        - Project 6: mos/powerpoint-2016/exam-1/project-6.md
        - Project 7: mos/powerpoint-2016/exam-1/project-7.md
      - Practice Exam 2:
        - Project 1: mos/powerpoint-2016/exam-2/project-1.md
        - Project 2: mos/powerpoint-2016/exam-2/project-2.md
        - Project 3: mos/powerpoint-2016/exam-2/project-3.md
        - Project 4: mos/powerpoint-2016/exam-2/project-4.md
        - Project 5: mos/powerpoint-2016/exam-2/project-5.md
        - Project 6: mos/powerpoint-2016/exam-2/project-6.md
        - Project 7: mos/powerpoint-2016/exam-2/project-7.md
      - Practice Exam 3:
        - Project 1: mos/powerpoint-2016/exam-3/project-1.md
        - Project 2: mos/powerpoint-2016/exam-3/project-2.md
        - Project 3: mos/powerpoint-2016/exam-3/project-3.md
        - Project 4: mos/powerpoint-2016/exam-3/project-4.md
        - Project 5: mos/powerpoint-2016/exam-3/project-5.md
        - Project 6: mos/powerpoint-2016/exam-3/project-6.md
        - Project 7: mos/powerpoint-2016/exam-3/project-7.md
      # - PowerPoint 2016 Core Practice Exam 2 Training:
      # - PowerPoint 2016 Core Practice Exam 3 Training:
  # - Setup:
  #   - setup/index.md
  #   - Changing the colors: setup/changing-the-colors.md
  #   - Changing the fonts: setup/changing-the-fonts.md
  #   - Changing the language: setup/changing-the-language.md
  #   - Changing the logo and icons: setup/changing-the-logo-and-icons.md
  #   - Ensuring data privacy: setup/ensuring-data-privacy.md
  #   - Setting up navigation: setup/setting-up-navigation.md
  #   - Setting up site search: setup/setting-up-site-search.md
  #   - Setting up site analytics: setup/setting-up-site-analytics.md
  #   - Setting up social cards: setup/setting-up-social-cards.md
  #   - Setting up a blog: setup/setting-up-a-blog.md
  #   - Setting up tags: setup/setting-up-tags.md
  #   - Setting up versioning: setup/setting-up-versioning.md
  #   - Setting up the header: setup/setting-up-the-header.md
  #   - Setting up the footer: setup/setting-up-the-footer.md
  #   - Adding a git repository: setup/adding-a-git-repository.md
  #   - Adding a comment system: setup/adding-a-comment-system.md
  #   - Building an optimized site: setup/building-an-optimized-site.md
  #   - Building for offline usage: setup/building-for-offline-usage.md
  #   - Extensions:
  #     - setup/extensions/index.md
  #     - Python Markdown: setup/extensions/python-markdown.md
  #     - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  #   - Dependencies:
  #     - setup/dependencies/image-processing.md
  # - Reference:
  #   - reference/index.md
  #   - Admonitions: reference/admonitions.md
  #   - Annotations: reference/annotations.md
  #   - Buttons: reference/buttons.md
  #   - Code blocks: reference/code-blocks.md
  #   - Content tabs: reference/content-tabs.md
  #   - Data tables: reference/data-tables.md
  #   - Diagrams: reference/diagrams.md
  #   - Footnotes: reference/footnotes.md
  #   - Formatting: reference/formatting.md
  #   - Grids: reference/grids.md
  #   - Icons, Emojis: reference/icons-emojis.md
  #   - Images: reference/images.md
  #   - Lists: reference/lists.md
  #   - Math: reference/math.md
  #   - Tooltips: reference/tooltips.md
  # - Insiders:
  #   - insiders/index.md
  #   - Getting started:
  #     - Installation: insiders/getting-started.md
  #     - Changelog: insiders/changelog.md
  # - Blog:
  #   - blog/index.md
  #   - 2022:
  #     - blog/posts/blog-support-just-landed.md
  #     - blog/posts/chinese-search-support.md
  #   - 2021:
  #     - blog/posts/the-past-present-and-future.md
  #     - blog/posts/excluding-content-from-search.md
  #     - blog/posts/search-better-faster-smaller.md
